# Project information
site_name: yunussyasar
docs_dir: docs  # Where to find the English markdown files
site_dir: site  # Where to put the English HTML files
site_author: 'Asst. Prof. Dr. Uğur CORUH'
site_url: 'https://ucoruh.github.io/course-note-template/'

site_description_en: >-
    Course Notes Template

site_description_tr: >-
    Ders Notu Şablonu

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ucoruh/course-note-template'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 - 2022 Asst. Prof. Dr. Uğur CORUH

#theme:
#    name: material
#   logo: assets/images/favicon.png
#   favicon: images/favicon.png
#   palette:
#       primary: teal
#       accent: pink
#   language: en
#   feature:
#       tabs: true
#   font:
#       text: Roboto
        
# Configuration
theme: default
  name: material
  custom_dir: docs/overrides/
  #name: null
  #custom_dir: !ENV [THEME_DIR, "material"]
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Static files
  static_templates:
    - 404.html
    
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    
  palette:
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  
#  palette:
#   - media: "(prefers-color-scheme: light)"
#     scheme: default
#     toggle:
#       icon: material/toggle-switch-off-outline
#       name: Switch to dark mode
#   - media: "(prefers-color-scheme: dark)"
#     scheme: slate
#     toggle:
#       icon: material/toggle-switch
#       name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: logo
    #logo: assets/images/favicon.png
    
# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY_TEMPLATE
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ucoruh
    - icon: fontawesome/brands/bitbucket
      link: https://bitbucket.org/ucoruh/
    - icon: fontawesome/regular/compass
      link: https://www.scopus.com/authid/detail.uri?authorId=57218950743
    - icon: fontawesome/regular/id-card
      link: https://dblp.org/pid/230/0394.html
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ucoruh/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/my-orcid?orcid=0000-0003-4193-8401
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ugurcoruh/
    - icon: fontawesome/regular/moon
      link: https://publons.com/researcher/1540204/ugur-coruh/
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=KIU4ltMAAAAJ&hl=tr
    - icon: fontawesome/regular/clipboard
      link: https://avesis.erdogan.edu.tr/ugur.coruh
    - icon: fontawesome/regular/user-circle
      link: https://www.ugurcoruh.com/
            
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite:
      guess_lang: true

plugins:
  - mkdocs-video #https://pypi.org/project/mkdocs-video/
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        default:
          name: English
          build: true
        en:
          name: English
          build: true
          site_name: "RTEU Course Notes Templates (en)"
        tr:
          name: Türkçe
          build: true
          site_name: "RTEU Ders Notu Şablonu (tr)"
      nav_translations:
        tr:
          Home: 'Ana Sayfa'
          Syllabus: 'Ders İzlencesi'
          Course Modules: 'Ders Modülleri'
          Week-1 (Sample-1): 'Hafta-1 (Örnek-1)'
          Week-2 (Sample-2): 'Hafta-2 (Örnek-1)'
          Week-3 (Sample-3): 'Hafta-3 (Örnek-1)'
          Week-4 (Sample-4): 'Hafta-4 (Örnek-1)'
          Week-5 (Sample-5): 'Hafta-5 (Örnek-1)'
          Week-6 (Sample-6): 'Hafta-6 (Örnek-1)'
          Week-7 (Sample-7): 'Hafta-7 (Örnek-1)'
          Week-8 (Midterm): 'Hafta-8 (Vize)'
          Week-9 (Sample-9): 'Hafta-9 (Örnek-1)'
          Week-10 (Sample-10): 'Hafta-10 (Örnek-1)'
          Week-11 (Sample-11): 'Hafta-11 (Örnek-1)'
          Week-12 (Sample-12): 'Hafta-12 (Örnek-1)'
          Week-13 (Sample-13): 'Hafta-13 (Örnek-1)'
          Week-14 (Sample-14): 'Hafta-14 (Örnek-1)'
          Week-15 (Sample-15): 'Hafta-15 (Örnek-1)'
          Week-16 (Final): 'Hafta-16 (Final)'
          License: 'Lisans'
          Resume: 'Özgeçmiş'
          Changelog: 'Geçmiş'
  - git-revision-date-localized
  - minify:
      minify_html: false
  #- with-pdf:
      #author: Dr. Uğur CORUH
      #copyright: ANY TEXT
      #
      #cover: false
      #back_cover: true
      #cover_title: TITLE TEXT
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
# Page tree
nav:
  - Home: index.md
  - Syllabus: syllabus/syllabus.md
  - Course Modules:
    - Week-1 (Sample-1): week-1/week-1.md
    - Week-2 (Sample-2): week-2/week-2.md
    - Week-3 (Sample-3): week-3/week-3.md
    - Week-4 (Sample-4): week-4/week-4.md
    - Week-5 (Sample-5): week-5/week-5.md
    - Week-6 (Sample-6): week-6/week-6.md
    - Week-7 (Sample-7): week-7/week-7.md
    - Week-8 (Midterm): week-8/week-8-midterm.md
    - Week-9 (Sample-9): week-9/week-9.md
    - Week-10 (Sample-10): week-10/week-10.md 
    - Week-11 (Sample-11): week-11/week-11.md 
    - Week-12 (Sample-12): week-12/week-12.md
    - Week-13 (Sample-13): week-13/week-13.md
    - Week-14 (Sample-14): week-14/week-14.md
    - Week-15 (Sample-15): week-15/week-15.md
    - Week-16 (Final): week-16/week-16-final.md
  - License: license.md
  - Resume: resume/index.md
  - Changelog: changelog/index.md
